#ifndef _COMMON_H_

#define_COMMON_H_
#include<graphics.h>
#include<stdio.h>
#include<math.h>
#include<conio.h>
#include<stdlib.h>
#include<bios.h>
#include <dos.h>
#include<string.h>
#include<time.h>
#include"CURSOR.h"
#include"mouse.h"
#include"INTI.h"
#include"mainloop.h"
#include"draw.h"
#include"hz.h"
#include"HZPUT.h"
#include"INSERT.h"
#include"FUNC.h"
#include"FILE.h"
#include"SEEKBAR.h"
#include"view.h"

#endif
